# iris 데이터 예측

In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [6]:
x, y = load_iris(return_X_y=True)
x, y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [7]:
import pandas as pd

In [8]:
iris = load_iris()

In [10]:
iris_data = iris.data
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
iris_label = iris.target

In [12]:
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [17]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label,
                                                test_size=0.2, random_state=11)

In [20]:
from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf.fit(x_train, y_train)

DecisionTreeClassifier(random_state=11)

In [21]:
dt_clf.feature_importances_

array([0.02500521, 0.        , 0.04867657, 0.92631822])

In [24]:
pred = dt_clf.predict(x_test)
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [25]:
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(pred, y_test)

0.9333333333333333

# iris data 이용해 교차검증

In [27]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np
import pandas as pd

In [29]:
iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features, label, test_size=0.2, random_state=11)

kfold = KFold(n_splits=5)
cv_accuracy = []

for i, j in kfold.split(x_train):
    train_x, test_x = x_train[i], x_train[j]
    train_y, test_y = y_train[i], y_train[j]
    dt_clf.fit(train_x, train_y)
    pred = dt_clf.predict(test_x)
    accuracy = np.round(accuracy_score(test_y, pred), 4)
    cv_accuracy.append(accuracy)
print(cv_accuracy)
print(np.mean(cv_accuracy))

[0.875, 0.9583, 1.0, 0.9167, 0.9583]
0.94166


In [43]:
kfold = KFold(n_splits=3)
cv_accuracy = []
n_iter = 0

for train_index, test_index in kfold.split(features):
    n_iter += 1
    x_train, x_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    cv_accuracy.append(accuracy)
    print(f'\n{n_iter}번째 정확도 {accuracy}  , 학습데이터 크기 {x_train.shape[0]}, 검증데이터 크기 {x_test.shape[0]}')
    print(f'\n {n_iter}번째 검증데이터 인덱스 {test_index} ')
# print(accuracy)
# print(cv_accuracy)
# np.mean(cv_accuracy)


1번째 정확도 0.0  , 학습데이터 크기 100, 검증데이터 크기 50

 1번째 검증데이터 인덱스 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 

2번째 정확도 0.0  , 학습데이터 크기 100, 검증데이터 크기 50

 2번째 검증데이터 인덱스 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99] 

3번째 정확도 0.0  , 학습데이터 크기 100, 검증데이터 크기 50

 3번째 검증데이터 인덱스 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149] 


In [44]:
from sklearn.model_selection import StratifiedKFold

sfk = StratifiedKFold(n_splits=3)
cv_accuracy = []
n_iter = 0

for train_index, test_index in sfk.split(features, label):
    n_iter += 1
    x_train, x_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    cv_accuracy.append(accuracy)
    
print(accuracy)
print(cv_accuracy)
np.mean(cv_accuracy)

0.98
[0.98, 0.94, 0.98]


0.9666666666666667

In [45]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

features = iris_data.data
label = iris_data.target

scores = cross_val_score(dt_clf, features, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도 :', np.round(scores,4))
print('평균 검증 정확도 :', np.round(np.mean(scores),4))

교차 검증별 정확도 : [0.98 0.94 0.98]
평균 검증 정확도 : 0.9667


In [52]:
from sklearn.model_selection import GridSearchCV

iris = load_iris()
x_train, x_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target,
                                                   test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()
parameters = {'max_depth' : [1,2,3], 'min_samples_split' : [2,3]}

import pandas as pd

grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit = True)

grid_dtree.fit(x_train, y_train)
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score','split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [49]:
estimator = grid_dtree.best_estimator_

pred = estimator.predict(x_test)
print('테스트 데이터 세트 정확도 : {0:.4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도 : 0.9667


In [54]:
from sklearn.datasets import make_classification
import matplotlib.pyplot as plt

x, y = make_classification(n_samples=300, n_features=2, n_informative=2,
                          n_redundant=0, n_clusters_per_class=1, random_state=42,
                          n_classes=3)
print(len(x))

300


In [55]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier()
parameters = {'max_depth' : [1,2,3], 'min_samples_split' : [2,3]}

grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

grid_dtree.fit(x_train,y_train)
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score','split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.625000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.625000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.891667                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.891667                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.912500                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.912500                1   

   split0_test_score  split1_test_score  split2_test_score  
0             0.6125              0.625             0.6375  
1             0.6125              0.625             0.6375  
2             0.8875              0.875             0.9125  
3             0.8875              0.875             0.9125  
4             0.9000              0.875             0.9625  
5             0.9000              0.875             0.9625

In [56]:
pred = grid_dtree.predict(x_test)

accuracy_score(y_test, pred)

0.95

In [62]:
diabet_df = pd.read_csv('./datasets/diabetes (2).csv')

diabet_df.head(1)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1

In [63]:
features = diabet_df.drop('Outcome', axis=1)
label = diabet_df['Outcome']

In [65]:
x_train, x_test, y_train, y_test = train_test_split(features, label, test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier()

parameters = {'max_depth' : [1,2,3], 'min_samples_split': [2,3]}

grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

grid_dtree.fit(x_train, y_train)
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score','split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.711701                3   
1  {'max_depth': 1, 'min_samples_split': 3}         0.711701                3   
2  {'max_depth': 2, 'min_samples_split': 2}         0.723139                1   
3  {'max_depth': 2, 'min_samples_split': 3}         0.723139                1   
4  {'max_depth': 3, 'min_samples_split': 2}         0.695441                5   
5  {'max_depth': 3, 'min_samples_split': 3}         0.695441                5   

   split0_test_score  split1_test_score  split2_test_score  
0           0.731707           0.707317           0.696078  
1           0.731707           0.707317           0.696078  
2           0.731707           0.707317           0.730392  
3           0.731707           0.707317           0.730392  
4           0.707317           0.682927           0.696078  
5           0.707317           0.682927           0.696078

In [70]:
pred = grid_dtree.predict(x_test)

accuracy_score(y_test, pred)

0.7727272727272727

In [71]:
from sklearn.preprocessing import LabelEncoder
items = ['TV', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)
print(encoder.classes_)

[0 3 4 2 2 1 1]
['TV' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [72]:
encoder.inverse_transform([1,1,1,2,3,4])

array(['믹서', '믹서', '믹서', '선풍기', '전자렌지', '컴퓨터'], dtype='<U4')

In [78]:
from sklearn.preprocessing import OneHotEncoder

items = ['TV', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
 
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

labels = labels.reshape(-1,1)

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
(7, 5)


In [83]:
items = [['TV', 1], ['전자렌지', 2], ['컴퓨터', 3], ['선풍기', 4], ['선풍기', 4], ['믹서', 5], ['믹서', 5]]
items_1 = [['TV', 1], ['전자렌지', 2], ['컴퓨터', 3], ['선풍기', 4], ['믹서', 5]]

oh_encoder = OneHotEncoder()
oh_encoder.fit(items_1)
oh_labels = oh_encoder.transform(items)
print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]]
(7, 10)


In [84]:
df = pd.DataFrame({'items' : ['TV', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
df

items
0    TV
1  전자렌지
2   컴퓨터
3   선풍기
4   선풍기
5    믹서
6    믹서

In [85]:
pd.get_dummies(df['items'])

TV  믹서  선풍기  전자렌지  컴퓨터
0   1   0    0     0    0
1   0   0    0     1    0
2   0   0    0     0    1
3   0   0    1     0    0
4   0   0    1     0    0
5   0   1    0     0    0
6   0   1    0     0    0

In [88]:
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [91]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
iris_df_scaled.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count       1.500000e+02      1.500000e+02       1.500000e+02   
mean       -1.468455e-15     -1.823726e-15      -1.610564e-15   
std         1.003350e+00      1.003350e+00       1.003350e+00   
min        -1.870024e+00     -2.433947e+00      -1.567576e+00   
25%        -9.006812e-01     -5.923730e-01      -1.226552e+00   
50%        -5.250608e-02     -1.319795e-01       3.364776e-01   
75%         6.745011e-01      5.586108e-01       7.627583e-01   
max         2.492019e+00      3.090775e+00       1.785832e+00   

       petal width (cm)  
count      1.500000e+02  
mean      -9.473903e-16  
std        1.003350e+00  
min       -1.447076e+00  
25%       -1.183812e+00  
50%        1.325097e-01  
75%        7.906707e-01  
max        1.712096e+00

In [93]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
iris_df_scaled.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            0.428704          0.440556           0.467458   
std             0.230018          0.181611           0.299203   
min             0.000000          0.000000           0.000000   
25%             0.222222          0.333333           0.101695   
50%             0.416667          0.416667           0.567797   
75%             0.583333          0.541667           0.694915   
max             1.000000          1.000000           1.000000   

       petal width (cm)  
count        150.000000  
mean           0.458056  
std            0.317599  
min            0.000000  
25%            0.083333  
50%            0.500000  
75%            0.708333  
max            1.000000

In [95]:
df_titanic = pd.read_csv('./datasets/titanic_train.csv')

In [97]:
df_titanic = df_titanic.loc[:, ['Survived', 'Sex', 'Age', 'Pclass']]
X = df_titanic.loc[:,['Sex', 'Age', 'Pclass']]
y = df_titanic['Survived']

In [98]:
X['Age'].fillna(method='ffill', inplace=True)

In [99]:
encoder = LabelEncoder()
labels = encoder.fit_transform(X['Sex'])
X['Sex']= labels

In [102]:
sclaer = MinMaxScaler()
scaler.fit(X[['Age']])
age_scaled = scaler.transform(X[['Age']])
X['Age']=age_scaled
X

Sex       Age  Pclass
0      1  0.271174       3
1      0  0.472229       1
2      0  0.321438       3
3      0  0.434531       1
4      1  0.434531       3
..   ...       ...     ...
886    1  0.334004       2
887    0  0.233476       1
888    0  0.233476       3
889    1  0.321438       1
890    1  0.396833       3

[891 rows x 3 columns]

In [105]:
dt_clf = DecisionTreeClassifier(random_state=156)
scores = cross_val_score(dt_clf, X, y, scoring='accuracy', cv=5)
scores.mean()

0.7889962965287804

In [106]:
test_titanic = pd.read_csv('./datasets/titanic_test.csv')
X_test = test_titanic.loc[:,['Sex', 'Age', 'Pclass']]

# 결측값 채우기
X_test['Age'].fillna(method='ffill', inplace=True)

# Label Encoding - Sex
encoder = LabelEncoder()
labels = encoder.fit_transform(X_test['Sex'])
X_test['Sex'] = labels

# feature Scaling - Age
scaler = MinMaxScaler()
age = np.array(X_test['Age']).reshape(-1, 1)
age = scaler.fit_transform(age)
X_test['Age'] = age