# LabelEncoding
- sklearn.preprocessing.LabelEncoder
- class sklearn.preprocessing.LabelEncoder

## 인코딩

In [26]:
from sklearn.preprocessing import LabelEncoder

items = ['TV','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값 :', labels)
print('인코딩 클래스 :', encoder.classes_)

인코딩 변환값 : [0 3 4 2 2 1 1]
인코딩 클래스 : ['TV' '믹서' '선풍기' '전자렌지' '컴퓨터']


## 디코딩
- inverse_transform(y)

In [27]:
encoder.inverse_transform([1,1,1,2,3,4])

array(['믹서', '믹서', '믹서', '선풍기', '전자렌지', '컴퓨터'], dtype='<U4')

# One Hot Encoding
- 원-핫 인코딩을 할 땐 2차원 데이터로 변환하는 등 작업을 해 줘야 함

## 방법 1

In [28]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# 먼저 숫자값으로 변환을 위해 Label Encoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2차원 데이터로 변환
labels = labels.reshape(-1,1)

# 원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원 - 핫 인코딩 데이터 : ', oh_labels.toarray())
print('원 - 핫 인코딩 데이터 차원 : ', oh_labels.shape)

원 - 핫 인코딩 데이터 :  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
원 - 핫 인코딩 데이터 차원 :  (7, 5)


## 방법 2 - 숫자로 바꿔서

In [30]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = [['TV', 1], ['전자렌지', 2], ['컴퓨터', 3], ['선풍기', 4], ['선풍기', 4], ['믹서', 5], ['믹서', 5]]
items_1 = [['TV', 1], ['전자렌지', 2], ['컴퓨터', 3], ['선풍기', 4], ['믹서', 5]]

# 원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(items_1)
oh_labels = oh_encoder.transform(items)
print('원 - 핫 인코딩 데이터 : ', oh_labels.toarray())
print('원 - 핫 인코딩 데이터 차원 : ', oh_labels.shape)

원 - 핫 인코딩 데이터 :  [[1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]]
원 - 핫 인코딩 데이터 차원 :  (7, 10)


## 판다스에서 지원하는 원-핫 인코딩

In [23]:
import pandas as pd

df = pd.DataFrame({'items' : ['TV', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
df

items
0    TV
1  전자렌지
2   컴퓨터
3   선풍기
4   선풍기
5    믹서
6    믹서

In [24]:
pd.get_dummies(df['items'])

TV  믹서  선풍기  전자렌지  컴퓨터
0   1   0    0     0    0
1   0   0    0     1    0
2   0   0    0     0    1
3   0   0    1     0    0
4   0   0    1     0    0
5   0   1    0     0    0
6   0   1    0     0    0