In [1]:
import numpy as np
from numpy.linalg import svd

# 4X4 Random 행렬 a 생성
np.random.seed(11)
a = np.random.randn(4,4)
print(np.round(a, 3))

[[ 1.749 -0.286 -0.485 -2.653]
 [-0.008 -0.32  -0.537  0.315]
 [ 0.421 -1.066 -0.886 -0.476]
 [ 0.69   0.561 -1.306 -1.119]]


In [4]:
U, Sigma, Vt = svd(a)

print(U.shape, Sigma.shape, Vt.shape)
print('U matrix:\n', np.round(U,3))
print('Sigma Value:\n', np.round(Sigma, 3))
print('V transpose matrix:\n', np.round(Vt, 3))

(4, 4) (4,) (4, 4)
U matrix:
 [[-0.859 -0.319  0.333 -0.223]
 [ 0.014  0.493 -0.072 -0.867]
 [-0.261  0.792  0.364  0.416]
 [-0.44   0.169 -0.867  0.161]]
Sigma Value:
 [3.693 1.39  1.182 0.115]
V transpose matrix:
 [[-0.519  0.074  0.329  0.786]
 [-0.08  -0.586 -0.743  0.313]
 [ 0.116 -0.8    0.581 -0.091]
 [-0.843 -0.1   -0.051 -0.526]]


In [5]:
# Sigma를 다시 0을 포함한 대칭행렬로 변환

Sigma_mat = np.diag(Sigma)
a_ = np.dot(np.dot(U, Sigma_mat), Vt)
print(np.round(a_, 3))

[[ 1.749 -0.286 -0.485 -2.653]
 [-0.008 -0.32  -0.537  0.315]
 [ 0.421 -1.066 -0.886 -0.476]
 [ 0.69   0.561 -1.306 -1.119]]


In [8]:
# 데이터 의존도가 높은 원본 데이터 행렬 생성

a[2] = a[0]+a[1]
a[3] = a[0]
print(np.round(a,3))

U, Sigma, Vt = svd(a)
print(U.shape, Sigma.shape, Vt.shape)
print('Sigma Value:\n', np.round(Sigma,3))

[[ 1.749 -0.286 -0.485 -2.653]
 [-0.008 -0.32  -0.537  0.315]
 [ 1.741 -0.606 -1.021 -2.338]
 [ 1.749 -0.286 -0.485 -2.653]]
(4, 4) (4,) (4, 4)
Sigma Value:
 [5.517 0.893 0.    0.   ]


In [9]:
# U 행렬의 경우는 Sigma와 내적을 수행하므로 Sigam의 앞 2행에 대응되는 앞 2열만 추출

U_ = U[:, :2]
Sigma_ = np.diag(Sigma[:2])

# V 전치 행렬의 경우는 앞 2행만 추출
Vt_ = Vt[:2]

# U, Sigma, Vt의 내적을 수행하며, 다시 원본 행렬 복원
a_ = np.dot(np.dot(U_, Sigma_), Vt_)
print(np.round(a_,3))

[[ 1.749 -0.286 -0.485 -2.653]
 [-0.008 -0.32  -0.537  0.315]
 [ 1.741 -0.606 -1.021 -2.338]
 [ 1.749 -0.286 -0.485 -2.653]]
