# 텍스트 불러와 토큰화 
- 토큰화하면 list 형태로 반환됨

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [11]:
text = '해보지 않으면 해낼 수 없다'

In [14]:
result = text_to_word_sequence(text, split=' ') # split으로 구분자 지정 (default=' ')
print('\n원문:\n', text)
print('\n토큰화:\n', result)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


# 단어 빈도수 세기

In [5]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.', '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.',
        '토큰화 한 결과는 딥러닝에서 사용할 수 있습니다.']

## 토큰화 함수를 이용해 전처리

In [6]:
token = Tokenizer() # 토큰화 함수 지정
token.fit_on_texts(docs) # 토큰화 함수 문장 적용

## 단어 빈도수 출력

In [15]:
print('\n단어 카운트:\n', token.word_counts)
print('\n문장 카운트: ', token.document_count)
print('\n각 단어가 몇개의 문장에 포함되어 있는가:\n', token.word_docs)
print('\n각 단어에 매겨진 인덱스 값:\n', token.word_index)


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 3), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])

문장 카운트:  3

각 단어가 몇개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'각': 1, '나누어': 1, '단어를': 1, '먼저': 1, '토큰화': 3, '합니다': 1, '텍스트의': 2, '딥러닝에서': 2, '해야': 1, '단어로': 1, '인식됩니다': 1, '결과는': 1, '수': 1, '한': 1, '있습니다': 1, '사용할': 1})

각 단어에 매겨진 인덱스 값:
 {'토큰화': 1, '텍스트의': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


# 문자의 원-핫 인코딩

In [17]:
text = '오랫동안 꿈꾸는 자는 그 꿈을 닮아간다'

In [19]:
token = Tokenizer()
token.fit_on_texts([text])
print('문장의 토큰화:', token.word_index)

문장의 토큰화: {'오랫동안': 1, '꿈꾸는': 2, '자는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


## 각 단어를 숫자화

In [28]:
x = token.texts_to_sequences([text])
print('문장의 숫자화: ', x)

문장의 숫자화:  [[1, 2, 3, 4, 5, 6]]


In [29]:
from keras.utils import to_categorical

word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes=word_size)
print('문장의 원-핫 인코딩:\n', x)

문장의 원-핫 인코딩:
 [[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]
